protected/controllers/AdminController.php
<?php


class AdminController extends BaseController
{
    private $repository;

    public function __construct($id, $module = null)
    {
        $this->repository = new NewsRepository();
        parent::__construct($id, $module);
    }

    public function filters()
    {
        return array(
            'accessControl', // perform access control for CRUD operations
        );
    }

    public function accessRules()
    {
        return array(
            array(
                'allow',
                'actions' => array('index', 'ajaxdelete', 'ajaxload', 'ajaxupdate'),
                'users' => array('admin'),
            ),
            array(
                'deny',  // deny all users
                'users' => array('*'),
            ),
        );
    }

    public function actionIndex()
    {
        $model = new News('search');
        $model->unsetAttributes();  // clear any default values

        $dataProvider = $this->repository->getAll($_GET['News'] ?? null);

        $this->render('index', array(
            'model' => $model,
            'dataProvider' => $dataProvider,
        ));
    }

    /**
     * Обновление записи
     * @throws CHttpException
     */
    public function actionAjaxUpdate()
    {
        if (Yii::app()->request->isPostRequest && isset($_POST['News'])) {
            $id = $_POST['News']['id'];
            $model = $this->repository->get($id);
            $model->attributes = $_POST['News'];
            if ($this->repository->save($model)) {
                $this->responseAsJSON(['success' => true]);
            }
            $this->responseAsJSON(['success' => false, 'errors' => $this->getModelErrors($model)]);
        } else {
            throw new CHttpException(400, 'bad request');
        }

    }

    /**
     * Загрузка формы для диалога редактирования
     * @throws CException
     * @throws CHttpException
     */
    public function actionAjaxLoad()
    {
        if (Yii::app()->request->isPostRequest && isset($_POST['id'])) {
            $id = Yii::app()->request->getPost('id');
            $model = $this->repository->get($id);
            Yii::app()->clientScript->scriptMap['jquery.js'] = false;
            Yii::app()->clientscript->scriptMap['jquery.min.js'] = false;
            $this->responseAsJSON([
                'success' => true,
                'form' => $this->renderPartial('_form', array('model' => $model, 'id' => $id), true, true)
            ]);


        } else {
            throw new CHttpException(400, 'bad request');
        }
    }

    /**
     * Удаление записи
     * @return array
     * @throws CDbException
     * @throws CHttpException
     */
    public function actionAjaxDelete()
    {
        if (Yii::app()->request->isPostRequest && isset($_POST['id'])) {
            $id = Yii::app()->request->getPost('id');
            $model = $this->repository->get($id);
            if ($this->repository->remove($model)) {
                $this->responseAsJSON(['success' => true]);
            }
            $this->responseAsJSON(['success' => false]);
        } else {
            throw new CHttpException(400, 'bad request');
        }

    }

}

protected/controllers/NewsController.php
<?php

class NewsController extends BaseController
{
    private $repository;

    public function __construct($id, $module = null)
    {
        $this->repository = new NewsRepository();
        parent::__construct($id, $module);
    }

    /**
     * @var string the default layout for the views. Defaults to '//layouts/column2', meaning
     * using two-column layout. See 'protected/views/layouts/column2.php'.
     */
    public $layout = '//layouts/column2';

    /**
     * @return array action filters
     */
    public function filters()
    {
        return array(
            'accessControl', // perform access control for CRUD operations
        );
    }

    /**
     * Specifies the access control rules.
     * This method is used by the 'accessControl' filter.
     * @return array access control rules
     */
    public function accessRules()
    {
        return array(
            array(
                'allow',
                'actions' => array('index', 'AjaxCreate'),
                'users' => array('*'),
            ),
            array(
                'deny',  // deny all users
                'users' => array('*'),
            ),
        );
    }

    /**
     * Создание поста
     * @throws CHttpException
     */
    public function actionAjaxCreate()
    {
        if (Yii::app()->request->isPostRequest && isset($_POST['News'])) {
            $model = new News;
            $model->attributes = $_POST['News'];
            if ($this->repository->save($model)) {
                $this->responseAsJSON(['success' => true]);
            }
            $this->responseAsJSON(['success' => false, 'errors' => $this->getModelErrors($model)]);
        } else {
            throw new CHttpException(400, 'bad request');
        }

    }


    /**
     * Lists all models.
     */
    public function actionIndex()
    {
        $model = new News;
        $dataProvider = $this->repository->getAll();
        $this->render('index', array(
            'dataProvider' => $dataProvider,
            'model' => $model,
        ));
    }
}

protected/views/layouts/column1.php
<?php /* @var $this Controller */ ?>
<?php $this->beginContent('//layouts/main'); ?>
<div id="content">
    <div id="alert" title="Attention" style="display: none">
        <p>New post.</p>
    </div>
	<?php echo $content; ?>
</div><!-- content -->
<?php $this->endContent(); ?>

protected/views/layouts/column2.php
<?php /* @var $this Controller */ ?>
<?php $this->beginContent('//layouts/main'); ?>
<div class="span-17">
	<div id="content">
		<?php echo $content; ?>
	</div><!-- content -->
</div>
<div class="span-7 last">
	<div id="sidebar">
	<?php
    echo $this->clips['sidebar'];
	?>
	</div><!-- sidebar -->
</div>
<?php $this->endContent(); ?>

protected/views/layouts/main.php
<?php /* @var $this Controller */ ?>
<!DOCTYPE html>
<html>
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
	<meta name="language" content="en">

	<!-- blueprint CSS framework -->
	<link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->request->baseUrl; ?>/css/screen.css" media="screen, projection">
	<link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->request->baseUrl; ?>/css/print.css" media="print">
	<!--[if lt IE 8]>
	<link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->request->baseUrl; ?>/css/ie.css" media="screen, projection">
	<![endif]-->

	<link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->request->baseUrl; ?>/css/main.css">
	<link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->request->baseUrl; ?>/css/form.css">

	<title><?php echo CHtml::encode($this->pageTitle); ?></title>
    <?php
    $cs = Yii::app()->clientScript;
    $cs->registerCoreScript('jquery.ui');
    $cs->registerCssFile($cs->getCoreScriptUrl(). '/jui/css/base/jquery-ui.css');
    ?>
    <?php Yii::app()->clientScript->registerPackage('test'); ?>
</head>

<body>

<div class="container" id="page">

	<div id="header">
		<div id="logo"><?php echo CHtml::encode(Yii::app()->name); ?></div>
	</div><!-- header -->

	<div id="mainmenu">
		<?php $this->widget('zii.widgets.CMenu',array(
			'items'=>array(
				array('label'=>'Feed', 'url'=>array('/news/index'), 'visible'=>Yii::app()->user->isGuest),
				array('label'=>'Login', 'url'=>array('/site/login'), 'visible'=>Yii::app()->user->isGuest),
				array('label'=>'Logout ('.Yii::app()->user->name.')', 'url'=>array('/site/logout'), 'visible'=>!Yii::app()->user->isGuest)
			),
		)); ?>
	</div><!-- mainmenu -->
	<?php if(isset($this->breadcrumbs)):?>
		<?php $this->widget('zii.widgets.CBreadcrumbs', array(
		    'homeLink' => Yii::app()->user->isGuest ? CHtml::link('News', array('/news/index')) : CHtml::link('News', array('/admin/index')),
			'links'=>$this->breadcrumbs,
		)); ?><!-- breadcrumbs -->
	<?php endif?>

	<?php echo $content; ?>

	<div class="clear"></div>

	<div id="footer">
		Copyright &copy; <?php echo date('Y'); ?> by My Company.<br/>
	</div><!-- footer -->

</div><!-- page -->

</body>
</html>